name: Build macOS App

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          python -m PyInstaller --onefile --windowed --icon=app.icns --name "Cards List Loader" versions/1.1.0_mac/app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Cards-List-Loader-macOS
          path: dist/*
